### ISSUE TITLE
can't build linux daemon

### ISSUE THREAD

**Issue by bumbacoin** [vcoin-z/virtualcoin#4]
can't build linux daemon

issue so far is
clientversion.h:13:0: warning: "CLIENT_VERSION_MINOR" redefined [enabled by default]
 #define CLIENT_VERSION_MINOR       13
 ^
clientversion.h:11:0: note: this is the location of the previous definition
 #define CLIENT_VERSION_MINOR       14

resulting in

alert.cpp:124:70: error: ‘CLIENT_VERSION’ was not declared in this scope
     return AppliesTo(PROTOCOL_VERSION, FormatSubVersion(CLIENT_NAME, CLIENT_VERSION, std::vector<std::string>()));

**Comment by ghost** [comment]
Hi, have you had the same problem as me, with the daemon building in linux? I use ubuntu 16.04, what version of linux do you use ?, I think all the currency code is wrong, with errors, because it is strange that it does not work with the dependencies that mentions, if supposedly, the dependencies for ubuntu and debian , I also wanted to build the daemon of this currency but until now it is impossible, I am new to linux, hoping that the developer or someone with more experience in this can be of help
